/* Cleanup */
/*
drop table user_room_access;
drop table room_inventory;
drop table deathstar_rooms;
drop table imperial_secrets;
drop table user_roles;
drop table roles;
drop table users;
*/

/* Create tables necessary for the demos */
create table deathstar.imperial_secrets (
  id integer generated by default on null as identity primary key,
  secret varchar2(4000) not null
);

create table deathstar.deathstar_rooms (
  id integer generated by default on null as identity primary key,
  name varchar2(200) not null,
  code varchar2(200) not null unique
);

create table deathstar.users
(
	id        integer,
	user_name varchar2(30 char)
);

create table deathstar.roles
(
	id        integer,
	role_name varchar2(30 char)
);

create table deathstar.user_roles
(
	id_user integer,
	id_role integer
);

create table user_room_access (
  id_user integer not null,
  id_room integer not null,
  constraint user_room_access_pk primary key ( id_user, id_room )
);

begin
	execute immediate 'create table deathstar.log_'||to_char(sysdate, 'YYYYMM')||' (
	  message varchar2(4000),
	  created timestamp default current_timestamp
	)';
end;
/

create or replace package deathstar.room_info as
  function get_room_id( i_name varchar2 ) return integer;
end;
/

-- Grants
grant execute on deathstar.room_info to public;